services:
  db:
    image: postgres:14
    container_name: chat_postgres
    volumes:
      - chat-db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"

  app:
    build:
      context: ./backend/
    working_dir: /go/src/app
    tty: true
    volumes:
      - ./backend:/go/src/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_NAME: postgres
    ports:
      - "8081:8081"
    depends_on:
      - db

  node:
    build:
      context: ./frontend/
    working_dir: /src/app/frontend
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/src/app/frontend
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app

volumes:
  chat-db-store: {}
